defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *defaults
  database: saas-metrics_dev

test:
  <<: *defaults
  database: saas-metrics_test

staging:
  <<: *defaults

production:
  <<: *defaults

dme_development:
  <<: *defaults
  database: dme

dme_production:
  <<: *defaults
  database: dme
  username: stats
  password: read.only-7368
  host: production.ckkephivaija.ap-southeast-1.rds.amazonaws.com